Add binding methods
panasyuk/sberbank-acquiring pull request #3
Opened 2019-12-03 10:55 UTC by PNixx

2019-12-09 07:59 UTC, panasyuk commented
@PNixx Привет. Расскажи пожалуйста подробнее об изменениях.

2019-12-09 10:06 UTC, PNixx commented
Получение списка привязанных карт к клиенту и возможность проведения автоплатежей.

2019-12-09 12:30 UTC, nikolaokonesh commented
@PNixx Привет! будет ли интрукция по автоплатежам?

2019-12-09 12:31 UTC, PNixx commented
@nikolaokonesh ну она описана в официальной документации https://securepayments.sberbank.ru/wiki/doku.php/integration:api:autopayment:start

2019-12-09 12:51 UTC, nikolaokonesh commented
@PNixx т.е. можно смело использовать автоплатеж? было бы хорошо иметь хоть простое представление на примере rails, было бы круто. А то в доке не разобрать

2019-12-09 13:18 UTC, PNixx commented
Я использую так:
```
    response = client.register({
      amount: 10000,
      orderNumber: "1",
      returnUrl: result_order_url,
      clientId: 1,
      features: 'AUTO_PAYMENT'
    }.compact)
    if response.success?
      response = client.payment_order_binding(mdOrder: response.data['orderId'], bindingId: card.binding_id)
      if response.success?
         ...
      end
    end
```

2019-12-11 15:24 UTC, panasyuk commented
Круто! А что, `/payment/rest/paymentOrderBinding.do` только через post работает? Они же обещали в доке поддержку обоих методов.

2019-12-11 15:30 UTC, PNixx commented
А я не пробовал, в доке написано post, так и сделал.

2019-12-11 15:32 UTC, panasyuk commented
Понял. Сейчас посмотрел тоже в доке и ничего не увидел по поводу GET. Нужно подумать. Либо тогда уже все на post переводить.

2019-12-11 15:53 UTC, panasyuk requested changes
Предлагаю попробовать оставить GET, потому что этот запрос, как и все остальные в их RESTful API, должен поддерживать оба метода.

2019-12-11 15:53 UTC, panasyuk commented on lib/sberbank/acquiring/request.rb
> +          @http_request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
😏 Тело запроса все равно передается в URI, а не в теле запроса. Раз работает, то не вижу смысла переходить на post. Как думаете? Может протестим GET и оставим?

2019-12-11 15:54 UTC, panasyuk commented
А еще не забывайте, что параметры для запроса можно задавать в underscore.

2019-12-11 16:00 UTC, PNixx commented on lib/sberbank/acquiring/request.rb
> +          @http_request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
`get_bindings` не работает с `get`, это я точно пробовал.

2019-12-11 16:26 UTC, panasyuk commented on lib/sberbank/acquiring/request.rb
> +          @http_request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
Ясненько. Будем думать.

2019-12-11 16:35 UTC, panasyuk commented on lib/sberbank/acquiring/request.rb
> +          @http_request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
Блин. Но параметры-то все равно в URI. Ладно постараемся переделать на POST.

2019-12-13 03:34 UTC, panasyuk commented on lib/sberbank/acquiring/request.rb
> +          @http_request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
Тогда предлагаю переписать все на Post. Чтобы все отправлялось в теле запроса. Возьметесь?

2019-12-13 05:57 UTC, PNixx commented on lib/sberbank/acquiring/request.rb
> +          @http_request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
А оно точно все будет работать через post? И что именно вам не нравится в такой реализации?

2019-12-15 05:10 UTC, panasyuk commented on lib/sberbank/acquiring/request.rb
> +          @http_request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
Меня просто смущает, что раньше все вызовы, согласно документации и реальному положению дел, работали и через GET, и через POST. Но теперь оказывается, что не все, раз `get_bindings` таки отказался работать через GET. К тому же документация обновилась, с тех пор как я ее помню, и все примеры там – через POST. Это значит что нет смысла в двух видах запросов и нужно просто использовать POST.
К тому же странно использовать POST, но тело запроса все равно отправлять в URI.
И самое главное – в этом случае не прийдется менять наш API: ни интерфейсы, ни сигнатуры методов, а только внутреннюю реализацию.
К тому же, нужно написать тесты на это дело.

2019-12-18 02:43 UTC, panasyuk commented on lib/sberbank/acquiring/request.rb
> +          @http_request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
Что думаете по этому поводу?

2020-04-05 05:53 UTC, panasyuk commented
@nikolaokonesh @PNixx Коллеги, переделал все на POST. Проверил только некоторые из запросов – работают. Пожалуйста, ответьте, сможете ли вы попробовать версию 1.0.0 https://github.com/panasyuk/sberbank-acquiring/tree/post_requests ?

2020-10-22 07:14 UTC, closed without merging